-- Licensed Materials - Property of IBM
--
-- BI and PM: CM
--
-- (C) Copyright IBM Corp. 2010
--
-- US Government Users Restricted Rights - Use, duplication or disclosure
-- restricted by GSA ADP Schedule Contract with IBM Corp.

-- Copyright (C) 2008 Cognos ULC, an IBM Company. All rights reserved.
-- Cognos (R) is a trademark of Cognos ULC, (formerly Cognos Incorporated).

-- Use this template to create the IBM Cognos content database. Replace these variables:  
-- C10CS : Database name
-- db2admin : User ID, this account is used by the product to connect to the content store
-- This script must be run as a user that has sufficient privileges to access and create the database. 
-- The database user account meeds to exist for the product to function.

CREATE DATABASE C10CS ALIAS C10CS USING CODESET UTF-8 TERRITORY US;
CHANGE DATABASE C10CS COMMENT WITH 'IBM Cognos Content Store';
CONNECT TO C10CS;
UPDATE DATABASE CONFIGURATION USING APPLHEAPSZ 1024 DEFERRED;
UPDATE DATABASE CONFIGURATION USING LOCKTIMEOUT 240 DEFERRED; 
CONNECT RESET;

CONNECT TO C10CS;
CREATE BUFFERPOOL C10CS_08KBP IMMEDIATE SIZE 1000 PAGESIZE 8K;
CREATE BUFFERPOOL C10CS_32KBP IMMEDIATE SIZE 1000 PAGESIZE 32K;
CONNECT RESET;

CONNECT TO C10CS;
CREATE SYSTEM TEMPORARY TABLESPACE TSN_SYS_C10CS IN DATABASE PARTITION GROUP IBMTEMPGROUP PAGESIZE 32K BUFFERPOOL C10CS_32KBP;
CREATE USER TEMPORARY TABLESPACE TSN_USR_C10CS IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 8K BUFFERPOOL C10CS_08KBP;
CREATE REGULAR TABLESPACE TSN_REG_C10CS IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 8K BUFFERPOOL C10CS_08KBP; 
CONNECT RESET;

CONNECT TO C10CS;
CREATE SCHEMA DB2COGNOS AUTHORIZATION db2admin;
COMMENT ON SCHEMA DB2COGNOS IS 'IBM Cognos Content Store';
REVOKE BINDADD ON DATABASE FROM PUBLIC;
REVOKE CREATETAB ON DATABASE FROM PUBLIC;
REVOKE CONNECT ON DATABASE FROM PUBLIC;
REVOKE IMPLICIT_SCHEMA ON DATABASE FROM PUBLIC;
REVOKE USE OF TABLESPACE USERSPACE1 FROM PUBLIC;
update db cfg for C10CS using dft_table_org row;
CONNECT RESET;
